FROM alpine:latest
WORKDIR /opt/slalite
COPY SLALite .

RUN mkdir /etc/slalite
COPY docker/slalite.yml /etc/slalite
RUN addgroup -S slalite && adduser -D -G slalite slalite
RUN chown -R slalite:slalite /etc/slalite && chmod 700 /etc/slalite

EXPOSE 8090

USER slalite
ENTRYPOINT ["/opt/slalite/SLALite"]

